### PR TITLE
chore: wrap log.Trace() with log.CheckTrace()

### PR DESCRIPTION
**Pull request by rpadrela**

### CODE REVIEW

**Comment by rpadrela** [comment]
@cbrisebois @tadej  checks were added around every log.Trace() call. Do we want these checks around all calls or just around the ones that do significant work just for the purpose of logging?

**Review by cbrisebois — APPROVED** [review]
looks good!

**Comment by cbrisebois** [comment]
> @cbrisebois @tadej checks were added around every log.Trace() call. Do we want these checks around all calls or just around the ones that do significant work just for the purpose of logging?

I think we should wrap all calls that are not error calls.  Warn and above should be dependent on the log level.  This means that we'd be essentially checking the log level, but I wonder if we should take the checks out of the functions anyway.

**Review by tadej — COMMENTED** [review]
LGTM

**Pull request merged**
